#!/data/data/com.termux/files/usr/bin/bash

figlet Hacking facebook

printf "

  Escoje una herramienta para hacer el phising:


    [ 1 ] shellphish
    [ 2 ] socialsploit
    [ 3 ] snacklab
    [ 4 ] "
