#!/data/data/com.termux/files/usr/bin/bash
clear
sleep 0.5
printf "\e[1;31m
 
     ███████ ]▄▄▄▄▄▄▄▄  "
     sleep 0.1
     printf "\e[0m
 ▂▄▅█████████▅▄▃▂"
 sleep 0.1
 printf "\e[1;31m
I███████████████████]."
sleep 0.1
printf "\e[1;90m
..◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤..................."
echo ""
echo ""
printf "\e[1;32m  LIBROS DISPONIBLES:\e[0m"
echo ""
printf "
  \e[1;31m [\e[0m 1 \e[1;31m] \e[0mProgramacion en bash."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 2\e[1;31m ] \e[0mProgramacion en python."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 3\e[1;31m ] \e[0mHacking etico 101."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 4\e[1;31m ] \e[0mProgramacion en php."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 5\e[1;31m ] \e[0mHacking desde cero." 
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 6\e[1;31m ] \e[0mVirus informaticos."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 7\e[1;31m ] \e[0mAtaques ciberneticos."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 8\e[1;31m ] \e[0mVirus y spam."
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 9\e[1;31m ] \e[0mJava desde cero."
  sleep 0.1
  printf "
  \e[1;31m[\e[0m 10\e[1;31m ] \e[0mLa caza hackers."
  sleep 0.1
  printf "
  \e[1;31m[\e[0m 11\e[1;31m ] \e[0mChema alonso."
  sleep 0.1
  printf "
  \e[1;31m[\e[0m 12\e[1;31m ] \e[0mSalir."
  echo
  echo
  sleep 0.1
read -p $' \e[1;31m🎭An๏\e[0mnym\e[1;31m๏uร🎭>> \e[0m' libros
apt install termux-open

case $libros in
	1)
