#!/data/data/com.termux/files/usr/bin/bash
sleep 0.5
printf "\e[1;31m
 
     ███████ ]▄▄▄▄▄▄▄▄  "
     sleep 0.1
     printf "\e[0m
 ▂▄▅█████████▅▄▃▂"
 sleep 0.1
 printf "\e[1;31m
I███████████████████]."
sleep 0.1
printf "\e[1;90m
..◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤..................."
echo ""
echo ""
printf "\e[1;32m  LIBROS DISPONIBLES:\e[0m"
echo ""
printf "
  \e[1;31m [\e[0m 1 \e[1;31m] \e[0mProgramacion en bash.       > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 2\e[1;31m ] \e[0mProgramacion en python.     > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 3\e[1;31m ] \e[0mPhishing 2017.              > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 4\e[1;31m ] \e[0mProgramacion en php.        > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 5\e[1;31m ] \e[0mHacking desde cero.         > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 6\e[1;31m ] \e[0mVirus informaticos.         > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 7\e[1;31m ] \e[0mAtaques ciberneticos.       > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 8\e[1;31m ] \e[0mProgramacion html.          > PDF"
  sleep 0.1
  printf "
  \e[1;31m [\e[0m 9\e[1;31m ] \e[0mJava desde cero.            > PDF"
  sleep 0.1
  printf "
  \e[1;31m[\e[0m 10\e[1;31m ] \e[0mLa caza hackers.            > PDF"
  sleep 0.1
  printf "
  \e[1;31m[\e[0m 11\e[1;31m ] \e[0mChema alonso.               > PDF"
  sleep 0.1
  printf "
  \e[1;31m[\e[0m 12\e[1;31m ] \e[0mSalir."
  echo
  echo
  sleep 0.1
read -p $' \e[1;31m🎭An๏\e[0mnym\e[1;31m๏uร🎭>> \e[0m' libros


case $libros in
	1)
		termux-open programacionbash.pdf
		sleep 6
		bash menu_7
		;;
	2)
	        termux-open programacionpython.pdf
		sleep 6
		bash menu_7
 		;;
	3)
		termux-open phishing2017.pdf
		sleep 6
		bash menu_7
		;;
	4)
		termux-open programacionphp.pdf
		sleep 6
		bash menu_7
                ;;
        5)
                termux-open hackingdesdecero.pdf
		sleep 6
		bash menu_7
                ;;
        6)
                termux-open virusinformaticos.pdf
		sleep 6
		bash menu_7
		;;
	7)
                termux-open ataquesciberneticos.pdf
		sleep 6
		bash menu_7
                ;;
        8)
                termux-open programacionhtml.pdf
		sleep 6
		bash menu_7
                ;;
        9)
		termux-open javadesdecero.pdf
		sleep 6
		bash menu_7
		;;
        10)
                termux-open lacazahackers.pdf
		sleep 6
		bash menu_7
                ;;
        11)
		termux-open chemaalonso.pdf 
		sleep 6
		bash menu_7
		;;

	12)
		exit
		;;

esac
