#!/data/data/con.termux/files/usr/bin/bash

figlet comandos
printf "
\e[1;32m
ls\e[1;90m

Listar el contenido de la carpteta."
sleep 0.4
printf "
\e[1;32m
pwd\e[1;90m

Muestra la ruta en en la carpeta en
la donde te encuentras."
sleep 0.4
printf "
\e[1;32m
cat
\e[1;90m
Permite leer(ver) el contenido de 
un archivo."
sleep 0.4                    
printf "
\e[1;32m
apt update
\e[1;90m
Supervisa la lista de nuevos
paquetes."
sleep 0.4                          
printf "
\e[1;32m
apt upgrade\e[1;90m

Instala(actualiza) los nuevos 
paquetes supervisados."
sleep 0.4                          
printf "
\e[1;32m
apt search\e[1;90m

Busca y muestra los paquetes 
disponibles."
sleep 0.4                  
printf "
\e[1;32m
apt install  < nombre del paquete >
\e[1;90m
Instala un paquete.
Tambien podemos instalar varios 
paquetes: Ejem: apt install nano
curl perl vim wget python2 -y."
sleep 0.4               
printf "
\e[1;32m
apt show  < nombre del paquete >
\e[1;90m
Muestra la información sobre un
paquete instalado."
sleep 0.4                           
printf "
\e[1;32m
apt list
\e[1;90m
Muestra todos los paquetes 
disponibles."
sleep 0.4                 
printf "
\e[1;32m
apt list –installed
\e[1;90m
Muestra todos los paquetes que 
ya han sido instalados."
sleep 0.4                    
printf "
\e[1;32m
apt remove  < nombre del paquete >
\e[1;90m
Elimina un achivo."
sleep 0.4                               
printf "
\e[1;32m
apt remove -r 
\e[1;90m
elimina un directorio."
sleep 0.4
printf "
\e[1;32m
cd ..
\e[1;90m
Retrocede un directorio."
sleep 0.4
printf "
\e[1;32m
mkdir  < nombre de la carpeta >
\e[1;90m
Crea crea un nuevo directorio
o carpeta."
sleep 0.4                                     
printf "
\e[1;32m
mv  < nombre >  < ruta >
\e[1;90m
Mueve una carpeta/archivo.

Ejem: mv carpeta1 /data/data/
com.termux/files/home.
pones ala ruta donde quieres 
llevar o mover tu directorio
o archivo.

Nota:
Usa el comando: mv --help
Para ver su menu de ayuda."
sleep 0.4
printf "
\e[1;32m
cp  < nombre del archivo >
\e[1;90m
Copia archivos y carpetas."
printf "\e[1;32m
________________________________________\e[0m "
printf "

      \e[1;35m [\e[0m 1 \e[1;35m] \e[0mContinuar.
      \e[1;35m [\e[0m 2 \e[1;35m] \e[0mMenu principal.
      \e[1;35m [\e[0m 3 \e[1;35m] \e[0mSalir."
echo
echo
read -p $'   \e[1;31mcom\e[0man\e[1;31mdos >> \e[0m ' etc

case $etc in
	1)
		cd ..
		bash snacklab.sh
		;;
	2)
		cd ..
		bash snacklab.sh
		;;
	3)
		exit
		;;
		
esac
